#!/usr/bin/env bash
export DISPLAY=:0.0

function connect(){
  xrandr --output VGA1 --auto --left-of LVDS1
}

function disconnect(){
  xrandr --output VGA1 --off
}

xrandr | grep "VGA1 connected" &> /dev/null && connect || disconnect
